// Copyright (C) 2019 Juan José Montiel
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "I don't like to use this if it's not necesary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "IN this class the sufix is correct", Scope = "type", Target = "~T:NvdaTestingDriver.KeyCombination")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.BrowseModesSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.DocumentFormattingSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.GeneralSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.InputCompositionSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.KeyboardSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.PresentationSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~P:NvdaTestingDriver.Settings.ProgressBarUpdateSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.ReviewCursorSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1623:Property summary documentation should match accessors", Justification = "In this case the official documentation extracted from the NVDA user manual is being used.", Scope = "type", Target = "~T:NvdaTestingDriver.Settings.SpeechSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "I think this warning is an error", Scope = "member", Target = "~M:NvdaTestingDriver.Settings.GeneralSettings.NvdaLanguage.op_Equality(NvdaTestingDriver.Settings.GeneralSettings.NvdaLanguage,NvdaTestingDriver.Settings.GeneralSettings.NvdaLanguage)~System.Boolean")]